<?php

namespace Pardalis\WaSUnitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AllianceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllianceRepository extends EntityRepository
{
}
