<?php

namespace Pardalis\WaSUnitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttackTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttackTypeRepository extends EntityRepository
{
}
