<?php

namespace Pardalis\WaSUnitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReleaseSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReleaseSetRepository extends EntityRepository
{
	public function getSetsWithSortedUnits() {
        return $this->getEntityManager()
            ->createQuery('SELECT s, u FROM PardalisWaSUnitBundle:ReleaseSet s JOIN s.units AS u ORDER BY s.id, u.number_in_set')
            ->getResult();
	}
}