<?php

namespace Pardalis\WaSUnitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnitTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitTypeRepository extends EntityRepository
{
	public function getTopLevelUnittypes() {
        return $this->getEntityManager()
            ->createQuery('SELECT t FROM PardalisWaSUnitBundle:UnitType t WHERE parent IS NULL')
            ->getResult();		
	}
}
