<?php

namespace Pardalis\WaSUnitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnitTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitTypeRepository extends EntityRepository
{
	public function getTopLevelUnittypes() {
        return $this->getEntityManager()
            ->createQuery('SELECT t FROM PardalisWaSUnitBundle:UnitType t WHERE parent IS NULL')
            ->getResult();		
	}

	public function getTopLevelUnittypesWithAbilitiesAndUnits() {
        return $this->getEntityManager()
            ->createQuery('SELECT t, a, u FROM PardalisWaSUnitBundle:UnitType t LEFT JOIN t.abilities AS a LEFT JOIN a.units AS u WHERE t.parent IS NULL')
            ->getResult();		
	}
}
