pardalis_was_nation_alliances:
    pattern:  /
    defaults: { _controller: PardalisWaSUnitBundle:Nation:index }

pardalis_was_unit_units:
    pattern:  /units
    defaults: { _controller: PardalisWaSUnitBundle:Unit:index }

pardalis_was_unit_viewunit:
    pattern:  /unit/{id}
    defaults: { _controller: PardalisWaSUnitBundle:Unit:unit }

pardalis_was_unit_unittypes:
    pattern:  /unittypes
    defaults: { _controller: PardalisWaSUnitBundle:Unit:unittypes }

pardalis_was_ability_abilities:
    pattern:  /abilities
    defaults: { _controller: PardalisWaSUnitBundle:Ability:index }

pardalis_was_attack_attacktypes:
    pattern:  /attacktypes
    defaults: { _controller: PardalisWaSUnitBundle:Attack:index }

pardalis_was_set_sets:
    pattern:  /sets
    defaults: { _controller: PardalisWaSUnitBundle:Set:index }

pardalis_was_rarity_rarities:
    pattern:  /rarities
    defaults: { _controller: PardalisWaSUnitBundle:Rarity:index }

pardalis_was_unit_bootstrap:
    pattern:  /bootstrap
    defaults: { _controller: PardalisWaSUnitBundle:Import:bootstrap }

pardalis_was_unit_import_alliances:
    pattern:  /importAlliances
    defaults: { _controller: PardalisWaSUnitBundle:Import:importAlliances }

pardalis_was_unit_import_sets:
    pattern:  /importSets
    defaults: { _controller: PardalisWaSUnitBundle:Import:importReleaseSets }

pardalis_was_unit_import_rarities:
    pattern:  /importRarities
    defaults: { _controller: PardalisWaSUnitBundle:Import:importRarities }

pardalis_was_unit_import_unittypes:
    pattern:  /importUnitTypes
    defaults: { _controller: PardalisWaSUnitBundle:Import:importUnitTypes }

pardalis_was_unit_import_attacktypes:
    pattern:  /importAttackTypes
    defaults: { _controller: PardalisWaSUnitBundle:Import:importAttackTypes }

pardalis_was_unit_import_abilities:
    pattern:  /importAbilities
    defaults: { _controller: PardalisWaSUnitBundle:Import:importAbilities }

pardalis_was_unit_import_units:
    pattern:  /importUnits
    defaults: { _controller: PardalisWaSUnitBundle:Import:importUnits }