parameters:
#    pardalis.wasunit.attackform.class: Pardalis\WaSUnitBundle\Entity\AttackForm

services:
#    pardalis_wa_s_unit.example:
#        class: %pardalis_wa_s_unit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

