parameters:
#    pardalis_wa_s_unit.example.class: Pardalis\WaSUnitBundle\Example

services:
#    pardalis_wa_s_unit.example:
#        class: %pardalis_wa_s_unit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
